server :
  port : 8088

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/call_name_system?serverTimezone=GMT%2b8
    username: root
    password: 1234


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 设置字符串结果类型为VARCHAR
#    use-column-label: true
  mapper-locations: classpath*:/mapper/*.xml

